// Comprehensive list of property types for Buy, Rent, and Lease

export const buyPropertyTypes = [
  { value: "villa", text: "Villa" },
  { value: "kothi", text: "Kothi" },
  { value: "flat", text: "Flat" },
  { value: "apartment", text: "Apartment" },
  { value: "independent_house", text: "Independent House" },
  { value: "duplex", text: "Duplex" },
  { value: "penthouse", text: "Penthouse" },
  { value: "studio_apartment", text: "Studio Apartment" },
  { value: "land", text: "Land" },
  { value: "plot", text: "Plot" },
  { value: "agricultural_land", text: "Agricultural Land" },
  { value: "commercial_land", text: "Commercial Land" },
  { value: "residential_land", text: "Residential Land" },
  { value: "industrial_land", text: "Industrial Land" },
  { value: "office", text: "Office" },
  { value: "commercial_space", text: "Commercial Space" },
  { value: "shop", text: "Shop" },
  { value: "showroom", text: "Showroom" },
  { value: "warehouse", text: "Warehouse" },
  { value: "godown", text: "Godown" },
  { value: "factory", text: "Factory" },
  { value: "industrial_shed", text: "Industrial Shed" },
  { value: "commercial_property", text: "Commercial Property" },
  { value: "building", text: "Building" },
  { value: "farmhouse", text: "Farmhouse" },
  { value: "holiday_home", text: "Holiday Home" },
  { value: "guest_house", text: "Guest House" },
  { value: "serviced_apartment", text: "Serviced Apartment" },
  { value: "condominium", text: "Condominium" },
  { value: "townhouse", text: "Townhouse" },
  { value: "row_house", text: "Row House" },
  { value: "bungalow", text: "Bungalow" },
  { value: "plaza", text: "Plaza" },
  { value: "mall", text: "Mall" },
  { value: "it_park", text: "IT Park" },
  { value: "business_center", text: "Business Center" },
  { value: "hospital", text: "Hospital" },
  { value: "school", text: "School" },
  { value: "hotel", text: "Hotel" },
  { value: "resort", text: "Resort" },
  { value: "hostel", text: "Hostel" },
  { value: "pg", text: "PG" },
  { value: "guest_accommodation", text: "Guest Accommodation" },
  { value: "boarding_house", text: "Boarding House" },
  { value: "service_flat", text: "Service Flat" },
  { value: "paying_guest", text: "Paying Guest" },
  { value: "co_living", text: "Co-living Space" },
  { value: "shared_room", text: "Shared Room" },
  { value: "private_room", text: "Private Room" },
  { value: "single_room", text: "Single Room" },
  { value: "double_room", text: "Double Room" },
  { value: "triple_room", text: "Triple Room" },
  { value: "four_sharing", text: "Four Sharing" },
  { value: "five_plus_sharing", text: "Five Plus Sharing" },
];

export const rentPropertyTypes = [
  { value: "flat", text: "Flat" },
  { value: "apartment", text: "Apartment" },
  { value: "independent_room", text: "Independent Room" },
  { value: "pg", text: "PG" },
  { value: "hostel", text: "Hostel" },
  { value: "room", text: "Room" },
  { value: "bed", text: "Bed" },
  { value: "office", text: "Office" },
  { value: "commercial_space", text: "Commercial Space" },
  { value: "shop", text: "Shop" },
  { value: "showroom", text: "Showroom" },
  { value: "warehouse", text: "Warehouse" },
  { value: "godown", text: "Godown" },
  { value: "villa", text: "Villa" },
  { value: "kothi", text: "Kothi" },
  { value: "house", text: "House" },
  { value: "duplex", text: "Duplex" },
  { value: "studio", text: "Studio" },
  { value: "serviced_apartment", text: "Serviced Apartment" },
  { value: "condominium", text: "Condominium" },
  { value: "townhouse", text: "Townhouse" },
  { value: "farmhouse", text: "Farmhouse" },
  { value: "holiday_home", text: "Holiday Home" },
  { value: "guest_house", text: "Guest House" },
  { value: "co_living", text: "Co-living Space" },
  { value: "shared_room", text: "Shared Room" },
  { value: "private_room", text: "Private Room" },
  { value: "single_room", text: "Single Room" },
  { value: "double_room", text: "Double Room" },
  { value: "triple_room", text: "Triple Room" },
  { value: "four_sharing", text: "Four Sharing" },
  { value: "five_plus_sharing", text: "Five Plus Sharing" },
  { value: "boys_hostel", text: "Boys Hostel" },
  { value: "girls_hostel", text: "Girls Hostel" },
  { value: "co_ed_hostel", text: "Co-ed Hostel" },
  { value: "boys_pg", text: "Boys PG" },
  { value: "girls_pg", text: "Girls PG" },
  { value: "co_ed_pg", text: "Co-ed PG" },
];

export const leasePropertyTypes = [
  { value: "land", text: "Land" },
  { value: "plot", text: "Plot" },
  { value: "agricultural_land", text: "Agricultural Land" },
  { value: "commercial_land", text: "Commercial Land" },
  { value: "industrial_land", text: "Industrial Land" },
  { value: "residential_land", text: "Residential Land" },
  { value: "warehouse", text: "Warehouse" },
  { value: "godown", text: "Godown" },
  { value: "factory", text: "Factory" },
  { value: "industrial_shed", text: "Industrial Shed" },
  { value: "industrial_unit", text: "Industrial Unit" },
  { value: "office", text: "Office" },
  { value: "commercial_space", text: "Commercial Space" },
  { value: "shop", text: "Shop" },
  { value: "showroom", text: "Showroom" },
  { value: "mall", text: "Mall" },
  { value: "plaza", text: "Plaza" },
  { value: "it_park", text: "IT Park" },
  { value: "business_center", text: "Business Center" },
  { value: "building", text: "Building" },
  { value: "hotel", text: "Hotel" },
  { value: "resort", text: "Resort" },
  { value: "hospital", text: "Hospital" },
  { value: "school", text: "School" },
  { value: "college", text: "College" },
  { value: "institution", text: "Institution" },
  { value: "restaurant", text: "Restaurant" },
  { value: "cafe", text: "Cafe" },
  { value: "bakery", text: "Bakery" },
  { value: "clinic", text: "Clinic" },
  { value: "pharmacy", text: "Pharmacy" },
  { value: "petrol_pump", text: "Petrol Pump" },
  { value: "service_station", text: "Service Station" },
  { value: "cold_storage", text: "Cold Storage" },
  { value: "transport_hub", text: "Transport Hub" },
  { value: "guest_house", text: "Guest House" },
  { value: "banquet_hall", text: "Banquet Hall" },
  { value: "conference_hall", text: "Conference Hall" },
  { value: "event_venue", text: "Event Venue" },
  { value: "sports_complex", text: "Sports Complex" },
  { value: "gym", text: "Gym" },
  { value: "spa", text: "Spa" },
  { value: "salon", text: "Salon" },
  { value: "laundry", text: "Laundry" },
  { value: "printing_press", text: "Printing Press" },
  { value: "call_center", text: "Call Center" },
  { value: "bpo_space", text: "BPO Space" },
  { value: "shared_office", text: "Shared Office" },
  { value: "coworking_space", text: "Coworking Space" },
  { value: "virtual_office", text: "Virtual Office" },
];

// PG specific options with detailed configurations
export const pgTypes = [
  // Girls PG Options
  { value: "girls_pg_with_food", text: "Girls PG - with Food" },
  { value: "girls_pg_without_food", text: "Girls PG - without Food" },
  { value: "girls_pg_single_sharing_with_food", text: "Girls PG - Single Sharing with Food" },
  { value: "girls_pg_single_sharing_without_food", text: "Girls PG - Single Sharing without Food" },
  { value: "girls_pg_double_sharing_with_food", text: "Girls PG - Double Sharing with Food" },
  { value: "girls_pg_double_sharing_without_food", text: "Girls PG - Double Sharing without Food" },
  { value: "girls_pg_triple_sharing_with_food", text: "Girls PG - Triple Sharing with Food" },
  { value: "girls_pg_triple_sharing_without_food", text: "Girls PG - Triple Sharing without Food" },
  { value: "girls_pg_four_sharing_with_food", text: "Girls PG - Four Sharing with Food" },
  { value: "girls_pg_four_sharing_without_food", text: "Girls PG - Four Sharing without Food" },
  { value: "girls_pg_ac", text: "Girls PG - AC" },
  { value: "girls_pg_non_ac", text: "Girls PG - Non AC" },
  { value: "girls_pg_attached_bathroom", text: "Girls PG - Attached Bathroom" },
  { value: "girls_pg_common_bathroom", text: "Girls PG - Common Bathroom" },
  
  // Boys PG Options
  { value: "boys_pg_with_food", text: "Boys PG - with Food" },
  { value: "boys_pg_without_food", text: "Boys PG - without Food" },
  { value: "boys_pg_single_sharing_with_food", text: "Boys PG - Single Sharing with Food" },
  { value: "boys_pg_single_sharing_without_food", text: "Boys PG - Single Sharing without Food" },
  { value: "boys_pg_double_sharing_with_food", text: "Boys PG - Double Sharing with Food" },
  { value: "boys_pg_double_sharing_without_food", text: "Boys PG - Double Sharing without Food" },
  { value: "boys_pg_triple_sharing_with_food", text: "Boys PG - Triple Sharing with Food" },
  { value: "boys_pg_triple_sharing_without_food", text: "Boys PG - Triple Sharing without Food" },
  { value: "boys_pg_four_sharing_with_food", text: "Boys PG - Four Sharing with Food" },
  { value: "boys_pg_four_sharing_without_food", text: "Boys PG - Four Sharing without Food" },
  { value: "boys_pg_ac", text: "Boys PG - AC" },
  { value: "boys_pg_non_ac", text: "Boys PG - Non AC" },
  { value: "boys_pg_attached_bathroom", text: "Boys PG - Attached Bathroom" },
  { value: "boys_pg_common_bathroom", text: "Boys PG - Common Bathroom" },
  
  // Co-ed PG Options
  { value: "co_ed_pg_with_food", text: "Co-ed PG - with Food" },
  { value: "co_ed_pg_without_food", text: "Co-ed PG - without Food" },
  { value: "co_ed_pg_single_sharing_with_food", text: "Co-ed PG - Single Sharing with Food" },
  { value: "co_ed_pg_single_sharing_without_food", text: "Co-ed PG - Single Sharing without Food" },
  { value: "co_ed_pg_double_sharing_with_food", text: "Co-ed PG - Double Sharing with Food" },
  { value: "co_ed_pg_double_sharing_without_food", text: "Co-ed PG - Double Sharing without Food" },
  { value: "co_ed_pg_triple_sharing_with_food", text: "Co-ed PG - Triple Sharing with Food" },
  { value: "co_ed_pg_triple_sharing_without_food", text: "Co-ed PG - Triple Sharing without Food" },
  { value: "co_ed_pg_four_sharing_with_food", text: "Co-ed PG - Four Sharing with Food" },
  { value: "co_ed_pg_four_sharing_without_food", text: "Co-ed PG - Four Sharing without Food" },
  { value: "co_ed_pg_ac", text: "Co-ed PG - AC" },
  { value: "co_ed_pg_non_ac", text: "Co-ed PG - Non AC" },
  
  // General PG Options
  { value: "pg_one_seater", text: "PG - One Seater" },
  { value: "pg_two_seater", text: "PG - Two Seater" },
  { value: "pg_three_seater", text: "PG - Three Seater" },
  { value: "pg_four_seater", text: "PG - Four Seater" },
  { value: "pg_five_seater", text: "PG - Five Seater" },
  { value: "pg_five_plus_seater", text: "PG - Five Plus Seater" },
  { value: "pg_premium", text: "Premium PG" },
  { value: "pg_economy", text: "Economy PG" },
  { value: "pg_luxury", text: "Luxury PG" },
  { value: "pg_standard", text: "Standard PG" },
  { value: "pg_budget", text: "Budget PG" },
  { value: "pg_near_metro", text: "PG - Near Metro" },
  { value: "pg_near_railway_station", text: "PG - Near Railway Station" },
  { value: "pg_near_bus_stand", text: "PG - Near Bus Stand" },
  { value: "pg_near_it_company", text: "PG - Near IT Company" },
  { value: "pg_near_college", text: "PG - Near College" },
  { value: "pg_near_school", text: "PG - Near School" },
  { value: "pg_with_wifi", text: "PG - with WiFi" },
  { value: "pg_with_laundry", text: "PG - with Laundry" },
  { value: "pg_with_meals", text: "PG - with Meals" },
  { value: "pg_with_power_backup", text: "PG - with Power Backup" },
  { value: "pg_with_security", text: "PG - with Security" },
  { value: "pg_with_parking", text: "PG - with Parking" },
  { value: "pg_with_ro_water", text: "PG - with RO Water" },
  { value: "pg_with_housekeeping", text: "PG - with Housekeeping" },
  { value: "pg_with_tv", text: "PG - with TV" },
  { value: "pg_with_refrigerator", text: "PG - with Refrigerator" },
  { value: "pg_with_ac", text: "PG - with AC" },
  { value: "pg_with_geyser", text: "PG - with Geyser" },
  { value: "pg_with_mattress", text: "PG - with Mattress" },
  { value: "pg_with_wardrobe", text: "PG - with Wardrobe" },
  { value: "pg_with_balcony", text: "PG - with Balcony" },
];

// Location/Area list for dropdowns
export const locationAreas = [
  { value: "model_town", text: "Model Town" },
  { value: "sarabha_nagar", text: "Sarabha Nagar" },
  { value: "gurdev_nagar", text: "Gurdev Nagar" },
  { value: "brs_nagar", text: "BRS Nagar" },
  { value: "civil_lines", text: "Civil Lines" },
  { value: "south_city", text: "South City" },
  { value: "pakhowal_road", text: "Pakhowal Road" },
  { value: "ferozepur_road", text: "Ferozepur Road" },
  { value: "dugri", text: "Dugri / Urban Estate Dugri" },
  { value: "rajguru_nagar", text: "Rajguru Nagar" },
  { value: "sector_39", text: "Sector-39 & Sector-39A" },
  { value: "hamidia_road", text: "Hamidia Road" },
  { value: "bhawani_nagar", text: "Bhawani Nagar" },
  { value: "ludhiana", text: "Ludhiana" },
  { value: "jalandhar", text: "Jalandhar" },
  { value: "amritsar", text: "Amritsar" },
  { value: "bathinda", text: "Bathinda" },
  { value: "pathankot", text: "Pathankot" },
  { value: "moga", text: "Moga" },
  { value: "firozpur", text: "Firozpur" },
  { value: "kapurthala", text: "Kapurthala" },
  { value: "hoshiarpur", text: "Hoshiarpur" },
  { value: "nawanshahr", text: "Nawanshahr" },
  { value: "batala", text: "Batala" },
  { value: "malerkotla", text: "Malerkotla" },
  { value: "sangrur", text: "Sangrur" },
  { value: "muktsar", text: "Muktsar" },
  { value: "faridkot", text: "Faridkot" },
  { value: "fatehgarh_sahib", text: "Fatehgarh Sahib" },
  { value: "rupnagar", text: "Rupnagar" },
  { value: "shahid_bhagat_singh_nagar", text: "Shahid Bhagat Singh Nagar" },
  { value: "tarn_taran", text: "Tarn Taran" },
  { value: "mansa", text: "Mansa" },
  { value: "budhladhana", text: "Budhladhana" },
];

// Budget Ranges for different transaction types
export const priceRangesBuy = [
  { value: "1", text: "₹10,00,000 - ₹25,00,000" },
  { value: "2", text: "₹25,00,000 - ₹50,00,000" },
  { value: "3", text: "₹50,00,000 - ₹1,00,00,000" },
  { value: "4", text: "₹1,00,00,000 - ₹2,00,00,000" },
  { value: "5", text: "₹2,00,00,000 - ₹5,00,00,000" },
  { value: "6", text: "₹5,00,00,000 - ₹10,00,00,000" },
  { value: "7", text: "₹10,00,00,000 Above" },
];

export const priceRangesRent = [
  { value: "1", text: "₹5,000 - ₹10,000" },
  { value: "2", text: "₹10,000 - ₹15,000" },
  { value: "3", text: "₹15,000 - ₹25,000" },
  { value: "4", text: "₹25,000 - ₹40,000" },
  { value: "5", text: "₹40,000 - ₹60,000" },
  { value: "6", text: "₹60,000 - ₹1,00,000" },
  { value: "7", text: "₹1,00,000 Above" },
];

export const priceRangesLease = [
  { value: "1", text: "₹50,000 - ₹2,00,000" },
  { value: "2", text: "₹2,00,000 - ₹5,00,000" },
  { value: "3", text: "₹5,00,000 - ₹10,00,000" },
  { value: "4", text: "₹10,00,000 - ₹25,00,000" },
  { value: "5", text: "₹25,00,000 - ₹50,00,000" },
  { value: "6", text: "₹50,00,000 - ₹1,00,00,000" },
  { value: "7", text: "₹1,00,00,000 Above" },
];

export const priceRangesPG = [
  { value: "1", text: "₹3,000 - ₹5,000" },
  { value: "2", text: "₹5,000 - ₹8,000" },
  { value: "3", text: "₹8,000 - ₹12,000" },
  { value: "4", text: "₹12,000 - ₹18,000" },
  { value: "5", text: "₹18,000 - ₹25,000" },
  { value: "6", text: "₹25,000 Above" },
];

// Combined export for easy imports
export const propertyTypes = {
  buy: buyPropertyTypes,
  rent: rentPropertyTypes,
  lease: leasePropertyTypes,
  pg: pgTypes,
};

export const searchOptions = {
  locations: locationAreas,
  priceRanges: {
    buy: priceRangesBuy,
    rent: priceRangesRent,
    lease: priceRangesLease,
    pg: priceRangesPG,
  },
};

export default propertyTypes;
